/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.practica8;

import javax.swing.JInternalFrame;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.Dimension;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


public class Practica8 extends javax.swing.JFrame {
    FileNameExtensionFilter filtro = null;
    JFileChooser fc = new JFileChooser();
    public boolean img; //Parametro para comprobar si hay una imagen abierta
    String nFichero = "";

    
    public Practica8() {
        initComponents();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        abrir = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        salir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        umbralizado = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );

        jMenu1.setText("Ficheros");

        abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        abrir.setText("Abrir Imagen");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        jMenu1.add(abrir);
        jMenu1.add(jSeparator1);

        salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jMenu1.add(salir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edición");

        umbralizado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        umbralizado.setText("Umbralizado");
        umbralizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umbralizadoActionPerformed(evt);
            }
        });
        jMenu2.add(umbralizado);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        System.out.println("Abrir Fichero");
        filtro = new FileNameExtensionFilter("Texto", "txt");
        fc.addChoosableFileFilter(filtro);
        filtro = new FileNameExtensionFilter("Imágenes", "jpg", "jpeg");
        fc.addChoosableFileFilter(filtro);
        int res = fc.showOpenDialog(null);
        if(res == JFileChooser.APPROVE_OPTION){
            System.out.println("Aceptar");
            File fichero = fc.getSelectedFile();
            System.out.println("Fichero: "+ fichero.getAbsolutePath());
            
            //Cerramos todas las ventanas que esten previamente abiertas
            JInternalFrame[] vectorVentanas = escritorio.getAllFrames();
            for(JInternalFrame ventana : vectorVentanas){
                ventana.dispose();
            }
            
            //Abrimos una nueva ventana con la imagen seleccionada
            VentanaInterna ventana = new VentanaInterna();
            nFichero = fichero + "";
            int x = ventana.abrirImagen(nFichero, fichero.getName());

            if(x == 0){
                img = true;                
                escritorio.add(ventana);
                ventana.setVisible(true);
                this.setPreferredSize(new Dimension(100, 1000));
            }
        }
        if(res == JFileChooser.CANCEL_OPTION){
            System.out.println("Cancelar");

        }
    }//GEN-LAST:event_abrirActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        int res3 = JOptionPane.showConfirmDialog(rootPane, "¿Seguro que desea salir?", "Salir de la aplicación", JOptionPane.YES_NO_OPTION);
        if(res3 == 0){
            System.exit(WIDTH);
        }
    }//GEN-LAST:event_salirActionPerformed

    private void umbralizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umbralizadoActionPerformed
        if(img ==false){
            JOptionPane.showMessageDialog(rootPane, "Primero debe abrir una imagen", "Error", JOptionPane.INFORMATION_MESSAGE);
        }else{
            String name = JOptionPane.showInputDialog(rootPane, "Introducir factor de umbralizado:", "Factor umbralizado", JOptionPane.OK_CANCEL_OPTION);
            System.out.println(name);
            
            VentanaInterna ventana = new VentanaInterna();
            ventana.getUmbral(Integer.parseInt(name), nFichero); 
            escritorio.add(ventana);
            ventana.setVisible(true);
            this.setPreferredSize(new Dimension(100, 1000));
        }
    }//GEN-LAST:event_umbralizadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Practica8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Practica8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Practica8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Practica8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Practica8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrir;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem salir;
    private javax.swing.JMenuItem umbralizado;
    // End of variables declaration//GEN-END:variables
}
